/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: volkanongun (https://sketchfab.com/volkanongun)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-cat-walk-13674c3dbb074f73b6563a75c28b0fe0
Title: Low Poly Cat Walk
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import catScene from "../assets/3d/low_poly_cat_walk.glb";

const Cat = ({ currentAnimation, ...props }) => {
  const group = useRef();
  const { scene, nodes, materials, animations } = useGLTF(catScene);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    Object.values(actions).forEach((action) => action.stop());

    if (actions[currentAnimation]) {
      actions[currentAnimation].play();
    }
  }, [actions, currentAnimation]);

  // useEffect(() => {
  //   if (!scene) return;
  //   scene.traverse((object) => {
  //     if (object.isMesh) {
  //       object.castShadow = true;
  //       object.receiveShadow = true;
  //     }
  //   });
  // }, [scene]);

  useEffect(() => {
    if (!scene) return;

    scene.traverse((object) => {
      if (object.isMesh) {
        if (object.material.name === "lambert4") {
          object.material.color.set("#b77250");
        }
      }
    });
  }, []);

  return (
    <group ref={group} {...props} dispose={null} castShadow receiveShadow>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="c71099cc41134ecf9d3d5594d3b3e153fbx"
            rotation={[Math.PI / 2, -0.7, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Cat_Root">
                  <group name="Cat_Root_Ctrl">
                    <group
                      name="Cat_Skeleton"
                      position={[0.008, -0.373, -0.778]}
                      scale={0.17}
                    >
                      <group name="Object_7">
                        <primitive object={nodes._rootJoint} />
                        <skinnedMesh
                          name="Object_56"
                          geometry={nodes.Object_56.geometry}
                          material={materials.lambert4}
                          skeleton={nodes.Object_56.skeleton}
                        />
                        <group name="Object_55" />
                      </group>
                    </group>
                  </group>
                  <group name="CatMesh" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

export default Cat;
