/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: alfance (https://sketchfab.com/alfance)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lowpoly-island-26c3f2f271ab41a5a0c9178ac5304df8
Title: Lowpoly island
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from "@react-spring/three";

const Island = (props) => {
  const { nodes, materials } = useGLTF("/lowpoly_island.glb");
  return (
    <a.group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials["Scene_-_Root"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </a.group>
  );
};

useGLTF.preload("/lowpoly_island.glb");

export default Island;
